---
- name: Laravel Setup
  hosts: All
  tasks:
    - name: Copy LAMP script to Local Server with ownership
      copy:
        src: deploy_lamp.sh
        dest: ~/deploy_lamp.sh
        mode: 0755

    - name: Create cron job to Check Server's uptime every 12AM
      cron:
        name: "Execute Cron Every 12AM"
        minute: "0"
        hour: "0"
        job: "uptime >> ~/uptime.log"

    - name: Check Server Uptime
      command: uptime -p
      register: uptime_out

    - name: Display the server Up-Time
      debug:
        var: uptime_out.stdout

    - name: Execute Laravel App Deployment Script
      shell: ~/deploy_lamp.sh

    - name: Verify PHP Application Accessibility using curl
      url: curl http://172.20.10.2
      register: php_app_response
      ignore_errors: true

    - name: Display Message if PHP Application is Accessible
      debug:
        msg: "PHP Application is Accessible"
      when: php_app_response.rc == 0